version: "3"

services: 
    app:
        build: .
        volumes:
            - .:/app
        ports: 
            - "5000:5000"
        env_file:
            - .env
            
        #networks:
        #    - proxy-manager-net
      
#networks:
#  proxy-manager-net:
#    external: true   
